core_index = numeric(0)
core_degree = numeric(0)
for(i in 1: length(degree(g))){
  if(length(neighbors(g,i))>200){
    core_index = c(core_index, i)
    core_degree = c(core_degree, length(neighbors(g,i)))
  }
}
g_node1 = induced.subgraph(g, c(1, neighbors(g,1)))
vertexvector = rep(3,vcount(g_node1))
vertexvector[1]=5
vertexcolor = rep("magenta",vcount(g_node1))
vertexcolor[1] ="black"
plot.igraph(g_node1,vertex.size=vertexvector,vertex.label =NA,vertex.color=vertexcolor)
n_node = vcount(g_node1)
n_edge = ecount(g_node1)
V(g)$name = V(g)
#core no.
max_average_degree = numeric(0)
max_clustering_coefficient = numeric(0)
max_density = numeric(0)
min_average_degree = numeric(0)
min_clustering_coefficient = numeric(0)
min_density = numeric(0)
max_index_average_degree = numeric(0)
max_index_clustering_coefficient = numeric(0)
max_index_density = numeric(0)
min_index_average_degree = numeric(0)
min_index_clustering_coefficient = numeric(0)
min_index_density = numeric(0)
for(i in 1:length(core_index))
{
core_neighbors =neighbors(g,core_index[i])
core_personal = induced.subgraph(g,c(core_index[i],core_neighbors))
core_community = walktrap.community(core_personal)
community_num_10up = numeric(0)
for(j in 1:length(core_community))
{
  community_number=V(core_personal)[which(core_community$membership==j)]
  if(length(community_number)>10)
  {
    community_num_10up = c(community_num_10up,j)
  }
}
average_degree = numeric(0)
global_clustering_coefficient = numeric(0)
density = numeric(0)
for(k in 1:length(community_num_10up))
{
  community_graph = induced.subgraph(core_personal,V(core_personal)[which(core_community$membership==community_num_10up[k])])
  average_degree = c(average_degree,mean(degree(community_graph))/vcount(community_graph))
  global_clustering_coefficient = c(global_clustering_coefficient,transitivity(community_graph,type="global"))
  density = c(density,graph.density(community_graph))
}
max_index_average_degree=c(max_index_average_degree,community_num_10up[which.max(average_degree)])
max_index_clustering_coefficient = c(max_index_clustering_coefficient,community_num_10up[which.max(global_clustering_coefficient)])
max_index_density=c(max_index_density,community_num_10up[which.max(density)])
min_index_average_degree=c(min_index_average_degree,community_num_10up[which.min(average_degree)])
min_index_clustering_coefficient = c(min_index_clustering_coefficient,community_num_10up[which.min(global_clustering_coefficient)])
min_index_density=c(min_index_density,community_num_10up[which.min(density)])
cat("max ")
cat("average_degree",community_num_10up[which.max(average_degree)]," ")
cat("cluster_coefficient",community_num_10up[which.max(global_clustering_coefficient)]," ")
cat("density",community_num_10up[which.max(density)],"\n")
cat("min ")
cat("average_degree",community_num_10up[which.min(average_degree)]," ")
cat("cluster_coefficient",community_num_10up[which.min(global_clustering_coefficient)]," ")
cat("density",community_num_10up[which.min(density)],"\n")
max_average_degree = c(max_average_degree,max(average_degree))
max_clustering_coefficient = c(max_clustering_coefficient,max(global_clustering_coefficient))
max_density = c(max_density,max(density))
min_average_degree = c(min_average_degree,min(average_degree))
min_clustering_coefficient = c(min_clustering_coefficient,min(global_clustering_coefficient))
min_density = c(min_density,min(density))
}
max_index_average_degree = t(data.matrix(max_index_average_degree))
max_index_clustering_coefficient = t(data.matrix(max_index_clustering_coefficient))
max_index_density = t(data.matrix(max_index_density))
min_index_average_degree = t(data.matrix(min_index_average_degree))
min_index_clustering_coefficient = t(data.matrix(min_index_clustering_coefficient))
min_index_density = t(data.matrix(min_index_density))
max_average_degree = t(data.matrix(max_average_degree))
max_clustering_coefficient = t(data.matrix(max_clustering_coefficient))
max_density = t(data.matrix(max_density))
min_average_degree = t(data.matrix(min_average_degree))
min_clustering_coefficient = t(data.matrix(min_clustering_coefficient))
min_density = t(data.matrix(min_density))
plot(max_average_degree)
plot(max_clustering_coefficient)
plot(max_density)